package co.id.keriss.request;

import co.id.keriss.fastpay.beans.request.DataTransaksi;
import co.id.keriss.fastpay.beans.request.Game;
import co.id.keriss.fastpay.beans.request.GantiPin;
import co.id.keriss.fastpay.beans.request.Inquery;
import co.id.keriss.fastpay.beans.request.Payment;
import co.id.keriss.fastpay.beans.request.Pulsa;
import co.id.keriss.fastpay.beans.respone.AsuransiRespone;
import co.id.keriss.fastpay.beans.respone.DataTransaksiRes;
import co.id.keriss.fastpay.beans.respone.GameRespone;
import co.id.keriss.fastpay.beans.respone.GantiPinRes;
import co.id.keriss.fastpay.beans.respone.KartuKredit;
import co.id.keriss.fastpay.beans.respone.MultiFinance;
import co.id.keriss.fastpay.beans.respone.PDAMRespone;
import co.id.keriss.fastpay.beans.respone.PLNPascaBayar;
import co.id.keriss.fastpay.beans.respone.PLNnonTagList;
import co.id.keriss.fastpay.beans.respone.PulsaRespone;
import co.id.keriss.fastpay.beans.respone.TVKabel;
import co.id.keriss.fastpay.beans.respone.TelPascaBayar;
import co.id.keriss.fastpay.beans.respone.TelkomGroup;

public class TestMain {
	public static void main(String[] args) {
		RequestBeans service = new RequestBeans();
		/*Pulsa pulsa = new Pulsa();
		pulsa.setKodeproduk("");
		pulsa.setNohp("");
		pulsa.setPin("");
		pulsa.setUid("");
		pulsa.setRef1("");
		service.getPulsaRespone(pulsa);*/
		//reqPulsaRespone();
		Inquery inquery = new Inquery();
		//Payment payment = new Payment();
		//reqDataTransaksiRes();
		//reqGameRespone();
		//reqGantiPinRes();
		//inquery = new Inquery();
		/*inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("071119223271");
		MultiFinance mf = reqMultiFinance(inquery);
		payment = new Payment();
		payment.setIDPelanggan1(mf.getIdpelanggan1());
		payment.setKodeProduk(mf.getKodeproduk());
		payment.setNominal(mf.getNominal());
		payment.setREF2(mf.getRef2());
		reqMultiFinance(payment);
		inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");*/
		//inquery.setIDPelanggan1("323360001351");
		//inquery.setIDPelanggan1("544100662064");
		//PLNnonTagList ptl = reqPLNnonTagList(inquery);
		/*payment = new Payment();
		payment.setIDPelanggan1(ptl.getIdpelanggan1());
		payment.setKodeProduk(ptl.getKodeproduk());
		payment.setNominal(ptl.getNominal());
		payment.setREF2(ptl.getRef2());
		reqPLNnonTagList(payment);*/
		
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("543300459551");
		PLNnonTagList ppb = reqPLNnonTagList(inquery);
		payment.setIDPelanggan1(ppb.getIdpelanggan1());
		payment.setKodeProduk(ppb.getKodeproduk());
		payment.setNominal(ppb.getNominal());
		payment.setPIN(inquery.getPIN());
		payment.setREF2(ppb.getRef2());
		reqPLNnonTagList(payment);*/
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("544102006867");
		PLNPascaBayar ppb = reqPLNPascaBayar(inquery);*/
		/*payment.setIDPelanggan1(ppb.getIdpelanggan1());
		payment.setKodeProduk(ppb.getKodeproduk());
		payment.setNominal(ppb.getNominal());
		payment.setREF2(ppb.getRef2());
		reqPLNPascaBayar(payment);*/
		
		
		//inquery = new Inquery();
		/*inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("544100662064");
		PLNPascaBayar ppb = reqPLNPraBayar(inquery);*/
		/*payment.setIDPelanggan1(ppb.getIdpelanggan1());
		payment.setKodeProduk(ppb.getKodeproduk());
		payment.setNominal(ppb.getNominal());
		payment.setREF2(ppb.getRef2());
		reqPLNPraBayar(payment);*/
		//reqPulsaRespone();
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("127202182124");
		TelkomGroup telkomvisi = reqTelkomGroup(inquery);*/
		/*payment.setIDPelanggan1(tg.getIdpelanggan1());
		payment.setKodeProduk(tg.getKodeproduk());
		payment.setNominal(tg.getNominal());
		payment.setREF2(tg.getRef2());
		reqTelkomGroup(payment);*/
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("08111009160");
		inquery.setKodeProduk("HPTSEL");*/
		//inquery.setIDPelanggan2("19547755");
		//TelPascaBayar tpb = reqTelPascaBayar(inquery);
		/*Payment payment = new Payment();
		payment.setUID(tpb.getUID());
		payment.setPIN(tpb.getPin());
		payment.setIDPelanggan1(tpb.getIdpelanggan1());
		payment.setKodeProduk(tpb.getKodeProduk());
		payment.setNominal(tpb.getNominal());
		payment.setREF2(tpb.getRef2());
		reqTelPascaBayar(payment);*/
		
		/*inquery.setUID("HH1234");
		inquery.setPIN("123456");
		inquery.setKodeProduk("ASRJWS");
		inquery.setIDPelanggan1("85000940901");
		inquery.setIDPelanggan2("");
		inquery.setIDPelanggan3("");
		inquery.setREF1("0");
		AsuransiRespone ar = reqAsuransiRespone(inquery);
		payment.setIDPelanggan3(ar.getIdpelanggan3());
		payment.setUID(inquery.getUID());
		payment.setPIN(inquery.getPIN());
		payment.setREF1(ar.getRef1());
		payment.setREF2(ar.getRef2());
		payment.setREF3(ar.getRef3());
		reqAsuransiRespone(payment);*/
		
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setKodeProduk("KKCITI");
		inquery.setIDPelanggan1("4096750000803016");
		KartuKredit kk = reqKartuKredit(inquery);
		payment = new Payment();
		payment.setIDPelanggan1(kk.getIdpelanggan1());
		payment.setKodeProduk(kk.getKodeproduk());
		payment.setNominal(kk.getNominal());
		payment.setPIN(inquery.getPIN());
		payment.setREF1(kk.getRef1());
		payment.setREF2(kk.getRef2());
		payment.setREF3(kk.getRef3());
		reqKartuKredit(payment);*/
		/*inquery = new Inquery();
		inquery.setUID("HH1234");
		inquery.setPIN("123456");
		inquery.setKodeProduk("FNFIF");
		inquery.setIDPelanggan1("85000940901");
		reqMultiFinance(inquery);*/
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("38859947758");
		PDAMRespone pr = reqPDAMRespone(inquery);
		payment = new Payment();
		payment.setIDPelanggan1(pr.getIdPelanggan1());
		payment.setKodeProduk(pr.getKodeProduksi());
		payment.setNominal(pr.getNominal());
		payment.setREF2(pr.getRef2());
		reqPDAMRespone(payment);*/
		inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("152701210588");
		//inquery.setIDPelanggan2("152701210588");
		inquery.setKodeProduk("SPEEDY");
		TelkomGroup telpon = reqTelkomGroup(inquery);
		/*inquery = new Inquery();
		inquery.setUID("HH57010");
		inquery.setPIN("130641");
		inquery.setIDPelanggan1("7000162882");
		TVKabel tvk = reqTVKabel(inquery);*/
		/*payment = new Payment();
		payment.setIDPelanggan1(telpon.getIdpelanggan1());
		payment.setKodeProduk(telpon.getKodeproduk());
		payment.setNominal(telpon.getNominal());
		payment.setREF2(telpon.getRef2());
		reqTVKabel(payment);*/
	}
	public static AsuransiRespone reqAsuransiRespone(Inquery inquery){
		System.out.println("\n\n\nAsuransiResponeInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		//inquery.setKodeProduk("ALLIANZ");
		AsuransiRespone ar = rp.getAnsuransiRespone(inquery);
		System.out.println(" 	getAdmincharge()	: "+	ar.getAdmincharge()	);
		System.out.println(" 	getAhliwarisaddress()	: "+	ar.getAhliwarisaddress()	);
		System.out.println(" 	getAhliwarisphonenumber()	: "+	ar.getAhliwarisphonenumber()	);
		System.out.println(" 	getBillamount()	: "+	ar.getBillamount()	);
		System.out.println(" 	getBilleradminfee()	: "+	ar.getBilleradminfee()	);
		System.out.println(" 	getBillercode()	: "+	ar.getBillercode()	);
		System.out.println(" 	getBillerrefnumber()	: "+	ar.getBillerrefnumber()	);
		System.out.println(" 	getBillquantity()	: "+	ar.getBillquantity()	);
		System.out.println(" 	getClaimamount()	: "+	ar.getClaimamount()	);
		System.out.println(" 	getCustomeradress()	: "+	ar.getCustomeradress()	);
		System.out.println(" 	getCustomerid()	: "+	ar.getCustomerid()	);
		System.out.println(" 	getCustomername()	: "+	ar.getCustomername()	);
		System.out.println(" 	getCustomerphonenumber()	: "+	ar.getCustomerphonenumber()	);
		System.out.println(" 	getIdpelanggan1()	: "+	ar.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	ar.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	ar.getIdpelanggan3()	);
		System.out.println(" 	getKeterangan()	: "+	ar.getKeterangan()	);
		System.out.println(" 	getKodeproduk()	: "+	ar.getKodeproduk()	);
		System.out.println(" 	getLastpaidduedate()	: "+	ar.getLastpaidduedate()	);
		System.out.println(" 	getLastpaidperiode()	: "+	ar.getLastpaidperiode()	);
		System.out.println(" 	getMiscfee()	: "+	ar.getMiscfee()	);
		System.out.println(" 	getMiscnumber()	: "+	ar.getMiscnumber()	);
		System.out.println(" 	getNominal()	: "+	ar.getNominal()	);
		System.out.println(" 	getNoref1()	: "+	ar.getNoref1()	);
		System.out.println(" 	getNoref2()	: "+	ar.getNoref2()	);
		System.out.println(" 	getPasswd()	: "+	ar.getPasswd()	);
		System.out.println(" 	getPenalty()	: "+	ar.getPenalty()	);
		System.out.println(" 	getPin()	: "+	ar.getPin()	);
		System.out.println(" 	getPpn()	: "+	ar.getPpn()	);
		System.out.println(" 	getProductcategory()	: "+	ar.getProductcategory()	);
		System.out.println(" 	getPtname()	: "+	ar.getPtname()	);
		System.out.println(" 	getRef1()	: "+	ar.getRef1()	);
		System.out.println(" 	getRef2()	: "+	ar.getRef2()	);
		System.out.println(" 	getRef3()	: "+	ar.getRef3()	);
		System.out.println(" 	getStampduty()	: "+	ar.getStampduty()	);
		System.out.println(" 	getStatus()	: "+	ar.getStatus()	);
		System.out.println(" 	getSwitcherid()	: "+	ar.getSwitcherid()	);
		System.out.println(" 	getUid()	: "+	ar.getUid()	);
		System.out.println(" 	getWaktu()	: "+	ar.getWaktu()	);
		return ar;
	}
	public static AsuransiRespone reqAsuransiRespone(Payment payment){
		System.out.println("\n\n\nAsuransiResponePayment ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		AsuransiRespone ar = rp.getAnsuransiRespone(payment);
		System.out.println(" 	getAdmincharge()	: "+	ar.getAdmincharge()	);
		System.out.println(" 	getAhliwarisaddress()	: "+	ar.getAhliwarisaddress()	);
		System.out.println(" 	getAhliwarisphonenumber()	: "+	ar.getAhliwarisphonenumber()	);
		System.out.println(" 	getBillamount()	: "+	ar.getBillamount()	);
		System.out.println(" 	getBilleradminfee()	: "+	ar.getBilleradminfee()	);
		System.out.println(" 	getBillercode()	: "+	ar.getBillercode()	);
		System.out.println(" 	getBillerrefnumber()	: "+	ar.getBillerrefnumber()	);
		System.out.println(" 	getBillquantity()	: "+	ar.getBillquantity()	);
		System.out.println(" 	getClaimamount()	: "+	ar.getClaimamount()	);
		System.out.println(" 	getCustomeradress()	: "+	ar.getCustomeradress()	);
		System.out.println(" 	getCustomerid()	: "+	ar.getCustomerid()	);
		System.out.println(" 	getCustomername()	: "+	ar.getCustomername()	);
		System.out.println(" 	getCustomerphonenumber()	: "+	ar.getCustomerphonenumber()	);
		System.out.println(" 	getIdpelanggan1()	: "+	ar.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	ar.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	ar.getIdpelanggan3()	);
		System.out.println(" 	getKeterangan()	: "+	ar.getKeterangan()	);
		System.out.println(" 	getKodeproduk()	: "+	ar.getKodeproduk()	);
		System.out.println(" 	getLastpaidduedate()	: "+	ar.getLastpaidduedate()	);
		System.out.println(" 	getLastpaidperiode()	: "+	ar.getLastpaidperiode()	);
		System.out.println(" 	getMiscfee()	: "+	ar.getMiscfee()	);
		System.out.println(" 	getMiscnumber()	: "+	ar.getMiscnumber()	);
		System.out.println(" 	getNominal()	: "+	ar.getNominal()	);
		System.out.println(" 	getNoref1()	: "+	ar.getNoref1()	);
		System.out.println(" 	getNoref2()	: "+	ar.getNoref2()	);
		System.out.println(" 	getPasswd()	: "+	ar.getPasswd()	);
		System.out.println(" 	getPenalty()	: "+	ar.getPenalty()	);
		System.out.println(" 	getPin()	: "+	ar.getPin()	);
		System.out.println(" 	getPpn()	: "+	ar.getPpn()	);
		System.out.println(" 	getProductcategory()	: "+	ar.getProductcategory()	);
		System.out.println(" 	getPtname()	: "+	ar.getPtname()	);
		System.out.println(" 	getRef1()	: "+	ar.getRef1()	);
		System.out.println(" 	getRef2()	: "+	ar.getRef2()	);
		System.out.println(" 	getRef3()	: "+	ar.getRef3()	);
		System.out.println(" 	getStampduty()	: "+	ar.getStampduty()	);
		System.out.println(" 	getStatus()	: "+	ar.getStatus()	);
		System.out.println(" 	getSwitcherid()	: "+	ar.getSwitcherid()	);
		System.out.println(" 	getUid()	: "+	ar.getUid()	);
		System.out.println(" 	getWaktu()	: "+	ar.getWaktu()	);
		return ar;
	}
	/*public static void reqCekSaldoRes(){
		System.out.println("\n\n\n");RequestBeans rp = new RequestBeans();
		Payment payment = new Payment();
		payment.setIDPelanggan1("38859947758");
		payment.setKodeProduk("WAAETRA");
		payment.setUID("130641");
	}*/
	public static void reqDataTransaksiRes(){
		System.out.println("\n\n\nDataTransaksiRes\n\n\n");
		RequestBeans rp = new RequestBeans();
		DataTransaksi dt = new DataTransaksi();
		//df.setIDPelanggan1("38859947758");
		dt.setKodeProduk("WAAETRA");
		dt.setUID("HH57010");
		dt.setPin("130641");
		DataTransaksiRes dtr = rp.getDataTransaksiRespone(dt);
		System.out.println("getIdpelanggan()	: "+	dtr.getIdpelanggan()	);
		System.out.println("getKeterangan()	: "+	dtr.getKeterangan()	);
		System.out.println("getKodeproduk()	: "+	dtr.getKodeproduk()	);
		System.out.println("getLimit()	: "+	dtr.getLimit()	);
		System.out.println("getPin()	: "+	dtr.getPin()	);
		System.out.println("getStatus()	: "+	dtr.getStatus()	);
		System.out.println("getTanggal1()	: "+	dtr.getTanggal1()	);
		System.out.println("getTanggal2()	: "+	dtr.getTanggal2()	);
		System.out.println("getUid()	: "+	dtr.getUid()	);
	}
	public static GameRespone reqGameRespone(){
		System.out.println("\n\n\nGameResponePayment ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		Game game = new Game();
		game.setKodeProduk("MS100");
		game.setUID("HH57010");
		game.setPIN("130641");
		GameRespone gr = rp.getGameRespone(game);
		System.out.println(" 	getKeterangan()	: "+	gr.getKeterangan()	);
		System.out.println(" 	getKodeProduksi()	: "+	gr.getKodeProduksi()	);
		System.out.println(" 	getNohp()	: "+	gr.getNohp()	);
		System.out.println(" 	getPin()	: "+	gr.getPin()	);
		System.out.println(" 	getRef1()	: "+	gr.getRef1()	);
		System.out.println(" 	getRef2()	: "+	gr.getRef2()	);
		System.out.println(" 	getSn()	: "+	gr.getSn()	);
		System.out.println(" 	getStatus()	: "+	gr.getStatus()	);
		System.out.println(" 	getUID()	: "+	gr.getUID()	);
		System.out.println(" 	getWaktu()	: "+	gr.getWaktu()	);
		return gr;
	}
	public static void reqGantiPinRes(){
		System.out.println("\n\n\nGantiPinRes ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		GantiPin gp = new GantiPin();
		gp.setPinBaru(gp.getPinLama());
		gp.setUid("HH57010");
		GantiPinRes gpr = rp.getGantiPinRespone(gp);
		System.out.println(" 	getKeterangan()	: "+	gpr.getKeterangan()	);
		System.out.println(" 	getPinbaru()	: "+	gpr.getPinbaru()	);
		System.out.println(" 	getPinlama()	: "+	gpr.getPinlama()	);
		System.out.println(" 	getStatus()	: "+	gpr.getStatus()	);
		System.out.println(" 	getUid()	: "+	gpr.getUid()	);
	}
	public static KartuKredit reqKartuKredit(Inquery inquery){
		System.out.println("\n\n\nKartuKreditInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		//inquery.setKodeProduk("KKCITI");
		KartuKredit kk = rp.getKartuKreditRespone(inquery);
		System.out.println("getIdpelanggan1()	: "+	kk.getIdpelanggan1()	);
		System.out.println("getIdpelanggan2()	: "+	kk.getIdpelanggan2()	);
		System.out.println("getIdpelanggan3()	: "+	kk.getIdpelanggan3()	);
		System.out.println("getKodeproduk()	: "+	kk.getKodeproduk()	);
		System.out.println("getNominal()	: "+	kk.getNominal()	);
		System.out.println("getPasswd()	: "+	kk.getPasswd()	);
		System.out.println("getPin()	: "+	kk.getPin()	);
		System.out.println("getRef1()	: "+	kk.getRef1()	);
		System.out.println("getRef2()	: "+	kk.getRef2()	);
		System.out.println("getRef3()	: "+	kk.getRef3()	);
		System.out.println("getUid()	: "+	kk.getUid()	);
		System.out.println("getWaktu()	: "+	kk.getWaktu()	);
		System.out.println("getStatus()	: "+	kk.getStatus()	);
		return kk;
	}
	public static KartuKredit reqKartuKredit(Payment payment){
		System.out.println("\n\n\nKartuKreditPayment ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		KartuKredit kk = rp.getKartuKreditRespone(payment);
		System.out.println("getIdpelanggan1()	: "+	kk.getIdpelanggan1()	);
		System.out.println("getIdpelanggan2()	: "+	kk.getIdpelanggan2()	);
		System.out.println("getIdpelanggan3()	: "+	kk.getIdpelanggan3()	);
		System.out.println("getKodeproduk()	: "+	kk.getKodeproduk()	);
		System.out.println("getNominal()	: "+	kk.getNominal()	);
		System.out.println("getPasswd()	: "+	kk.getPasswd()	);
		System.out.println("getPin()	: "+	kk.getPin()	);
		System.out.println("getRef1()	: "+	kk.getRef1()	);
		System.out.println("getRef2()	: "+	kk.getRef2()	);
		System.out.println("getRef3()	: "+	kk.getRef3()	);
		System.out.println("getUid()	: "+	kk.getUid()	);
		System.out.println("getWaktu()	: "+	kk.getWaktu()	);
		System.out.println("getWaktu()	: "+	kk.getWaktu()	);
		return kk;
	}
	public static MultiFinance reqMultiFinance(Inquery inquery){
		System.out.println("\n\n\nMultiFinanceInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setKodeProduk("FNWOM");
		MultiFinance mf = rp.getMutiFinanceRespone(inquery);
		System.out.println("getAdmincharge()	: "+	mf.getAdmincharge()	);
		System.out.println("getBiayaadmin()	: "+	mf.getBiayaadmin()	);
		System.out.println("getBillamount()	: "+	mf.getBillamount()	);
		System.out.println("getBilleradminFree()	: "+	mf.getBilleradminFree()	);
		System.out.println("getBillercode()	: "+	mf.getBillercode()	);
		System.out.println("getBillerrefnumber()	: "+	mf.getBillerrefnumber()	);
		System.out.println("getBillquantity()	: "+	mf.getBillquantity()	);
		System.out.println("getBranchname()	: "+	mf.getBranchname()	);
		System.out.println("getCarnumberl()	: "+	mf.getCarnumberl()	);
		System.out.println("getChasisnumber()	: "+	mf.getChasisnumber()	);
		System.out.println("getCustomerid()	: "+	mf.getCustomerid()	);
		System.out.println("getCustomername()	: "+	mf.getCustomername()	);
		System.out.println("getIdpelanggan1()	: "+	mf.getIdpelanggan1()	);
		System.out.println("getIdpelanggan2()	: "+	mf.getIdpelanggan2()	);
		System.out.println("getIdpelanggan3()	: "+	mf.getIdpelanggan3()	);
		System.out.println("getItennerktype()	: "+	mf.getItemmerktype()	);
		System.out.println("getKeterangan()	: "+	mf.getKeterangan()	);
		System.out.println("getKodeproduk()	: "+	mf.getKodeproduk()	);
		System.out.println("getLastpaidduedate544100662064()	: "+	mf.getLastpaidduedate()	);
		System.out.println("getLastpaidperiode()	: "+	mf.getLastpaidperiode()	);
		System.out.println("getMaximunpayamount()	: "+	mf.getMaximunpayamount()	);
		System.out.println("getMinmumpayamount()	: "+	mf.getMinmumpayamount()	);
		System.out.println("getMinorunit1()	: "+	mf.getMinorunit1()	);
		System.out.println("getMinorunit2()	: "+	mf.getMinorunit2()	);
		System.out.println("getMiscfee()	: "+	mf.getMiscfee()	);
		System.out.println("getNominal()	: "+	mf.getNominal()	);
		System.out.println("getNoref1()	: "+	mf.getNoref1()	);
		System.out.println("getNoref2()	: "+	mf.getNoref2()	);
		System.out.println("getOdinstallmentamount()	: "+	mf.getOdinstallmentamount()	);
		System.out.println("getOdpenaltyfee()	: "+	mf.getOdpenaltyfee()	);
		System.out.println("getOsdinstallmentperiod()	: "+	mf.getOsdinstallmentperiod()	);
		System.out.println("getOsinstallmentamount()	: "+	mf.getOsinstallmentamount()	);
		System.out.println("getPin()	: "+	mf.getPin()	);
		System.out.println("getPpn()	: "+	mf.getPpn()	);
		System.out.println("getProductcategory()	: "+	mf.getProductcategory()	);
		System.out.println("getPtname()	: "+	mf.getPtname()	);
		System.out.println("getRef1()	: "+	mf.getRef1()	);
		System.out.println("getRef2()	: "+	mf.getRef2()	);
		System.out.println("getRef3()	: "+	mf.getRef3()	);
		System.out.println("getStampduty()	: "+	mf.getStampduty()	);
		System.out.println("getStatus()	: "+	mf.getStatus()	);
		System.out.println("getSwitcherid()	: "+	mf.getSwitcherid()	);
		System.out.println("getTenor()	: "+	mf.getTenor()	);
		System.out.println("getUid()	: "+	mf.getUid()	);
		System.out.println("getWaktu()	: "+	mf.getWaktu()	);
		return mf;
	}
	public static MultiFinance reqMultiFinance(Payment payment){
		System.out.println("\n\n\nMultiFinancePayment ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("FNWOM");
		MultiFinance mf = rp.getMutiFinanceRespone(payment);
		System.out.println("getAdmincharge()	: "+	mf.getAdmincharge()	);
		System.out.println("getBiayaadmin()	: "+	mf.getBiayaadmin()	);
		System.out.println("getBillamount()	: "+	mf.getBillamount()	);
		System.out.println("getBilleradminFree()	: "+	mf.getBilleradminFree()	);
		System.out.println("getBillercode()	: "+	mf.getBillercode()	);
		System.out.println("getBillerrefnumber()	: "+	mf.getBillerrefnumber()	);
		System.out.println("getBillquantity()	: "+	mf.getBillquantity()	);
		System.out.println("getBranchname()	: "+	mf.getBranchname()	);
		System.out.println("getCarnumberl()	: "+	mf.getCarnumberl()	);
		System.out.println("getChasisnumber()	: "+	mf.getChasisnumber()	);
		System.out.println("getCustomerid()	: "+	mf.getCustomerid()	);
		System.out.println("getCustomername()	: "+	mf.getCustomername()	);
		System.out.println("getIdpelanggan1()	: "+	mf.getIdpelanggan1()	);
		System.out.println("getIdpelanggan2()	: "+	mf.getIdpelanggan2()	);
		System.out.println("getIdpelanggan3()	: "+	mf.getIdpelanggan3()	);
		System.out.println("getItennerktype()	: "+	mf.getItemmerktype()	);
		System.out.println("getKeterangan()	: "+	mf.getKeterangan()	);
		System.out.println("getKodeproduk()	: "+	mf.getKodeproduk()	);
		System.out.println("getLastpaidduedate()	: "+	mf.getLastpaidduedate()	);
		System.out.println("getLastpaidperiode()	: "+	mf.getLastpaidperiode()	);
		System.out.println("getMaximunpayamount()	: "+	mf.getMaximunpayamount()	);
		System.out.println("getMinmumpayamount()	: "+	mf.getMinmumpayamount()	);
		System.out.println("getMinorunit1()	: "+	mf.getMinorunit1()	);
		System.out.println("getMinorunit2()	: "+	mf.getMinorunit2()	);
		System.out.println("getMiscfee()	: "+	mf.getMiscfee()	);
		System.out.println("getNominal()	: "+	mf.getNominal()	);
		System.out.println("getNoref1()	: "+	mf.getNoref1()	);
		System.out.println("getNoref2()	: "+	mf.getNoref2()	);
		System.out.println("getOdinstallmentamount()	: "+	mf.getOdinstallmentamount()	);
		System.out.println("getOdpenaltyfee()	: "+	mf.getOdpenaltyfee()	);
		System.out.println("getOsdinstallmentperiod()	: "+	mf.getOsdinstallmentperiod()	);
		System.out.println("getOsinstallmentamount()	: "+	mf.getOsinstallmentamount()	);
		System.out.println("getPin()	: "+	mf.getPin()	);
		System.out.println("getPpn()	: "+	mf.getPpn()	);
		System.out.println("getProductcategory()	: "+	mf.getProductcategory()	);
		System.out.println("getPtname()	: "+	mf.getPtname()	);
		System.out.println("getRef1()	: "+	mf.getRef1()	);
		System.out.println("getRef2()	: "+	mf.getRef2()	);
		System.out.println("getRef3()	: "+	mf.getRef3()	);
		System.out.println("getStampduty()	: "+	mf.getStampduty()	);
		System.out.println("getStatus()	: "+	mf.getStatus()	);
		System.out.println("getSwitcherid()	: "+	mf.getSwitcherid()	);
		System.out.println("getTenor()	: "+	mf.getTenor()	);
		System.out.println("getUid()	: "+	mf.getUid()	);
		System.out.println("getWaktu()	: "+	mf.getWaktu()	);
		return mf;
	}
	public static PDAMRespone reqPDAMRespone(Inquery inquery){
		System.out.println("\n\n\nPDAMResponeInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setIDPelanggan1("38859947758");
		inquery.setKodeProduk("WAAETRA");
		PDAMRespone pdam = rp.getPDAMRespone(inquery);
		System.out.println("	mothperiod1 : " +	pdam.getMothperiod1());
		System.out.println("	mothperiod2 : " +	pdam.getMothperiod2());
		System.out.println("	mothperiod3 : " +	pdam.getMothperiod3());
		System.out.println("	mothperiod4 : " +	pdam.getMothperiod4());
		System.out.println("	mothperiod5 : " +	pdam.getMothperiod5());
		System.out.println("	mothperiod6 : " +	pdam.getMothperiod6());
		System.out.println("	nohp : " +	pdam.getNohp());
		System.out.println("	nominal : " +	pdam.getNominal());
		System.out.println("	noref1 : " +	pdam.getNoref1());
		System.out.println("	noref2 : " +	pdam.getNoref2());
		System.out.println("	pdamname : " +	pdam.getPdamname());
		System.out.println("	penalty1 : " +	pdam.getPenalty1());
		System.out.println("	penalty2 : " +	pdam.getPenalty2());
		System.out.println("	penalty3 : " +	pdam.getPenalty3());
		System.out.println("	penalty4 : " +	pdam.getPenalty4());
		System.out.println("	penalty5 : " +	pdam.getPenalty5());
		System.out.println("	penalty6 : " +	pdam.getPenalty6());
		System.out.println("	pin : " +	pdam.getPin());
		System.out.println("	ref1 : " +	pdam.getRef1());
		System.out.println("	ref2 : " +	pdam.getRef2());
		System.out.println("	ref3 : " +	pdam.getRef3());
		System.out.println("	sn : " +	pdam.getSn());
		System.out.println("	status : " +	pdam.getStatus());
		System.out.println("	switcherId : " +	pdam.getSwitcherId());
		System.out.println("	totalbillamount : " +	pdam.getTotalbillamount());
		System.out.println("	UID : " +	pdam.getUID());
		System.out.println("	waktu : " +	pdam.getWaktu());
		System.out.println("	yearperiod1 : " +	pdam.getYearperiod1());
		System.out.println("	yearperiod2 : " +	pdam.getYearperiod2());
		System.out.println("	yearperiod3 : " +	pdam.getYearperiod3());
		System.out.println("	yearperiod4 : " +	pdam.getYearperiod4());
		System.out.println("	yearperiod5 : " +	pdam.getYearperiod5());
		System.out.println("	yearperiod6 : " +	pdam.getYearperiod6());
		return pdam;
	}
	public static PDAMRespone reqPDAMRespone(Payment payment){
		System.out.println("\n\n\nPDAMResponePayment ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setIDPelanggan1("38859947758");
		payment.setKodeProduk("WAAETRA");
		PDAMRespone pdam = rp.getPDAMRespone(payment);
		System.out.println("	mothperiod1 : " +	pdam.getMothperiod1());
		System.out.println("	mothperiod2 : " +	pdam.getMothperiod2());
		System.out.println("	mothperiod3 : " +	pdam.getMothperiod3());
		System.out.println("	mothperiod4 : " +	pdam.getMothperiod4());
		System.out.println("	mothperiod5 : " +	pdam.getMothperiod5());
		System.out.println("	mothperiod6 : " +	pdam.getMothperiod6());
		System.out.println("	nohp : " +	pdam.getNohp());
		System.out.println("	nominal : " +	pdam.getNominal());
		System.out.println("	noref1 : " +	pdam.getNoref1());
		System.out.println("	noref2 : " +	pdam.getNoref2());
		System.out.println("	pdamname : " +	pdam.getPdamname());
		System.out.println("	penalty1 : " +	pdam.getPenalty1());
		System.out.println("	penalty2 : " +	pdam.getPenalty2());
		System.out.println("	penalty3 : " +	pdam.getPenalty3());
		System.out.println("	penalty4 : " +	pdam.getPenalty4());
		System.out.println("	penalty5 : " +	pdam.getPenalty5());
		System.out.println("	penalty6 : " +	pdam.getPenalty6());
		System.out.println("	pin : " +	pdam.getPin());
		System.out.println("	ref1 : " +	pdam.getRef1());
		System.out.println("	ref2 : " +	pdam.getRef2());
		System.out.println("	ref3 : " +	pdam.getRef3());
		System.out.println("	sn : " +	pdam.getSn());
		System.out.println("	status : " +	pdam.getStatus());
		System.out.println("	switcherId : " +	pdam.getSwitcherId());
		System.out.println("	totalbillamount : " +	pdam.getTotalbillamount());
		System.out.println("	UID : " +	pdam.getUID());
		System.out.println("	waktu : " +	pdam.getWaktu());
		System.out.println("	yearperiod1 : " +	pdam.getYearperiod1());
		System.out.println("	yearperiod2 : " +	pdam.getYearperiod2());
		System.out.println("	yearperiod3 : " +	pdam.getYearperiod3());
		System.out.println("	yearperiod4 : " +	pdam.getYearperiod4());
		System.out.println("	yearperiod5 : " +	pdam.getYearperiod5());
		System.out.println("	yearperiod6 : " +	pdam.getYearperiod6());
		return pdam;
	}
	public static PLNnonTagList reqPLNnonTagList(Inquery inquery){
		System.out.println("\n\n\nInquery PLNnonTagList .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setKodeProduk("PLNNON");
		PLNnonTagList plntl = rp.getResponePLNTaglist(inquery);
		System.out.println("getAdmincharge()	: "+	plntl.getAdmincharge());
		System.out.println("getAdminchargeminorunit()	: "+	plntl.getAdminchargeminorunit());
		System.out.println("getAreacode()	: "+	plntl.getAreacode());
		System.out.println("getBiayaadmin()	: "+	plntl.getBiayaadmin());
		System.out.println("getCustomerdetailminorunit1()	: "+	plntl.getCustomerdetailminorunit1());
		System.out.println("getCustomerdetailminorunit2()	: "+	plntl.getCustomerdetailminorunit2());
		System.out.println("getCustomerdetailode1()	: "+	plntl.getCustomerdetailode1());
		System.out.println("getCustomerdetailode2()	: "+	plntl.getCustomerdetailode2());
		System.out.println("getCustomerDetailvalueamount1()	: "+	plntl.getCustomerDetailvalueamount1());
		System.out.println("getCustomerDetailvalueamount2()	: "+	plntl.getCustomerDetailvalueamount2());
		System.out.println("getExpirationDate()	: "+	plntl.getExpirationDate());
		System.out.println("getIdpelanggan1()	: "+	plntl.getIdpelanggan1());
		System.out.println("getIdpelanggan2()	: "+	plntl.getIdpelanggan2());
		System.out.println("getIdpelanggan3()	: "+	plntl.getIdpelanggan3());
		System.out.println("getInfotext()	: "+	plntl.getInfotext());
		System.out.println("getKeterangan()	: "+	plntl.getKeterangan());
		System.out.println("getKodeproduk()	: "+	plntl.getKodeproduk());
		System.out.println("getMutationnumber()	: "+	plntl.getMutationnumber());
		System.out.println("getNominal()	: "+	plntl.getNominal());
		System.out.println("getPin()	: "+	plntl.getPin());
		System.out.println("getPlnbillminourunit()	: "+	plntl.getPlnbillminourunit());
		System.out.println("getPlnbillvalue()	: "+	plntl.getPlnbillvalue());
		System.out.println("getPlnrefnumber()	: "+	plntl.getPlnrefnumber());
		System.out.println("getPowerconsumingcategory()	: "+	plntl.getPowerconsumingcategory());
		System.out.println("getRef1()	: "+	plntl.getRef1());
		System.out.println("getRef2()	: "+	plntl.getRef2());
		System.out.println("getRef3()	: "+	plntl.getRef3());
		System.out.println("getRegistrationdate()	: "+	plntl.getRegistrationdate());
		System.out.println("getRegistrationnumber()	: "+	plntl.getRegistrationnumber());
		System.out.println("getServiceunit()	: "+	plntl.getServiceunit());
		System.out.println("getServiceunitaddress()	: "+	plntl.getServiceunitaddress());
		System.out.println("getServiceunitphone()	: "+	plntl.getServiceunitphone());
		System.out.println("getStatus()	: "+	plntl.getStatus());
		System.out.println("getSubcribername()	: "+	plntl.getSubcribername());
		System.out.println("getSubcribersegmentation()	: "+	plntl.getSubcribersegmentation());
		System.out.println("getSubscriberid()	: "+	plntl.getSubscriberid());
		System.out.println("getSwitcherId()	: "+	plntl.getSwitcherId());
		System.out.println("getSwrefnumber()	: "+	plntl.getSwrefnumber());
		System.out.println("getTotalrepeat()	: "+	plntl.getTotalrepeat());
		System.out.println("getTotaltransactionAmmountminor()	: "+	plntl.getTotaltransactionAmmountminor());
		System.out.println("getTotaltransactionamount()	: "+	plntl.getTotaltransactionamount());
		System.out.println("getTransactioncode()	: "+	plntl.getTransactioncode());
		System.out.println("getTransactionname()	: "+	plntl.getTransactionname());
		System.out.println("getUid()	: "+	plntl.getUid());
		System.out.println("getWaktu()	: "+	plntl.getWaktu());
		return plntl;
	}
	public static PLNnonTagList reqPLNnonTagList(Payment payment){
		System.out.println("\n\n\nPLNnonTagList .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setIDPelanggan1("38859947758");
		payment.setKodeProduk("PLNNON");
		PLNnonTagList plntl = rp.getResponePLNTaglist(payment);
		System.out.println("getAdmincharge()	: "+	plntl.getAdmincharge());
		System.out.println("getAdminchargeminorunit()	: "+	plntl.getAdminchargeminorunit());
		System.out.println("getAreacode()	: "+	plntl.getAreacode());
		System.out.println("getBiayaadmin()	: "+	plntl.getBiayaadmin());
		System.out.println("getCustomerdetailminorunit1()	: "+	plntl.getCustomerdetailminorunit1());
		System.out.println("getCustomerdetailminorunit2()	: "+	plntl.getCustomerdetailminorunit2());
		System.out.println("getCustomerdetailode1()	: "+	plntl.getCustomerdetailode1());
		System.out.println("getCustomerdetailode2()	: "+	plntl.getCustomerdetailode2());
		System.out.println("getCustomerDetailvalueamount1()	: "+	plntl.getCustomerDetailvalueamount1());
		System.out.println("getCustomerDetailvalueamount2()	: "+	plntl.getCustomerDetailvalueamount2());
		System.out.println("getExpirationDate()	: "+	plntl.getExpirationDate());
		System.out.println("getIdpelanggan1()	: "+	plntl.getIdpelanggan1());
		System.out.println("getIdpelanggan2()	: "+	plntl.getIdpelanggan2());
		System.out.println("getIdpelanggan3()	: "+	plntl.getIdpelanggan3());
		System.out.println("getInfotext()	: "+	plntl.getInfotext());
		System.out.println("getKeterangan()	: "+	plntl.getKeterangan());
		System.out.println("getKodeproduk()	: "+	plntl.getKodeproduk());
		System.out.println("getMutationnumber()	: "+	plntl.getMutationnumber());
		System.out.println("getNominal()	: "+	plntl.getNominal());
		System.out.println("getPin()	: "+	plntl.getPin());
		System.out.println("getPlnbillminourunit()	: "+	plntl.getPlnbillminourunit());
		System.out.println("getPlnbillvalue()	: "+	plntl.getPlnbillvalue());
		System.out.println("getPlnrefnumber()	: "+	plntl.getPlnrefnumber());
		System.out.println("getPowerconsumingcategory()	: "+	plntl.getPowerconsumingcategory());
		System.out.println("getRef1()	: "+	plntl.getRef1());
		System.out.println("getRef2()	: "+	plntl.getRef2());
		System.out.println("getRef3()	: "+	plntl.getRef3());
		System.out.println("getRegistrationdate()	: "+	plntl.getRegistrationdate());
		System.out.println("getRegistrationnumber()	: "+	plntl.getRegistrationnumber());
		System.out.println("getServiceunit()	: "+	plntl.getServiceunit());
		System.out.println("getServiceunitaddress()	: "+	plntl.getServiceunitaddress());
		System.out.println("getServiceunitphone()	: "+	plntl.getServiceunitphone());
		System.out.println("getStatus()	: "+	plntl.getStatus());
		System.out.println("getSubcribername()	: "+	plntl.getSubcribername());
		System.out.println("getSubcribersegmentation()	: "+	plntl.getSubcribersegmentation());
		System.out.println("getSubscriberid()	: "+	plntl.getSubscriberid());
		System.out.println("getSwitcherId()	: "+	plntl.getSwitcherId());
		System.out.println("getSwrefnumber()	: "+	plntl.getSwrefnumber());
		System.out.println("getTotalrepeat()	: "+	plntl.getTotalrepeat());
		System.out.println("getTotaltransactionAmmountminor()	: "+	plntl.getTotaltransactionAmmountminor());
		System.out.println("getTotaltransactionamount()	: "+	plntl.getTotaltransactionamount());
		System.out.println("getTransactioncode()	: "+	plntl.getTransactioncode());
		System.out.println("getTransactionname()	: "+	plntl.getTransactionname());
		System.out.println("getUid()	: "+	plntl.getUid());
		System.out.println("getWaktu()	: "+	plntl.getWaktu());
		return plntl;
	}
	public static PLNPascaBayar reqPLNPascaBayar(Inquery inquery){
		System.out.println("\n\n\nPLNPascaBayarInquery .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setKodeProduk("PLNPASC");
		PLNPascaBayar plb = rp.getPLNPascaBayarRespone(inquery);
		System.out.println(" getKodeproduk : "+ 	plb.getKodeproduk());
		System.out.println(" getWaktu : "+ 	plb.getWaktu());
		System.out.println(" getIdpelanggan1 : "+ 	plb.getIdpelanggan1());
		System.out.println(" getIdpelanggan2 : "+ 	plb.getIdpelanggan2());
		System.out.println(" getIdpelanggan3 : "+ 	plb.getIdpelanggan3());
		System.out.println(" getNominal : "+ 	plb.getNominal());
		System.out.println(" getBiayaadmin : "+ 	plb.getBiayaadmin());
		System.out.println(" getUid : "+ 	plb.getUid());
		System.out.println(" getPin : "+ 	plb.getPin());
		System.out.println(" getRef1 : "+ 	plb.getRef1());
		System.out.println(" getRef2 : "+ 	plb.getRef2());
		System.out.println(" getRef3 : "+ 	plb.getRef3());
		System.out.println(" getStatus : "+ 	plb.getStatus());
		System.out.println(" getKeterangan : "+ 	plb.getKeterangan());
		System.out.println(" getSwitcherId : "+ 	plb.getSwitcherId());
		System.out.println(" getSubscriberId : "+ 	plb.getSubscriberId());
		System.out.println(" getBillstatus : "+ 	plb.getBillstatus());
		System.out.println(" getPaymentstatus : "+ 	plb.getPaymentstatus());
		System.out.println(" getTotaloutstandingbell : "+ 	plb.getTotaloutstandingbell());
		System.out.println(" getSwereferencenumber : "+ 	plb.getSwereferencenumber());
		System.out.println(" getSubscribename : "+ 	plb.getSubscribename());
		System.out.println(" getServiceunit : "+ 	plb.getServiceunit());
		System.out.println(" getServiceunitphone : "+ 	plb.getServiceunitphone());
		System.out.println(" getSubscribeSegmentation : "+ 	plb.getSubscribeSegmentation());
		System.out.println(" getPowerconsumingcategory : "+ 	plb.getPowerconsumingcategory());
		System.out.println(" getTotaladmincharge : "+ 	plb.getTotaladmincharge());
		System.out.println(" getBlth1 : "+ 	plb.getBlth1());
		System.out.println(" getDuedate1 : "+ 	plb.getDuedate1());
		System.out.println(" getMeterreaddate1 : "+ 	plb.getMeterreaddate1());
		System.out.println(" getRptag1 : "+ 	plb.getRptag1());
		System.out.println(" getIncentive1 : "+ 	plb.getIncentive1());
		System.out.println(" getValuedatetax1 : "+ 	plb.getValuedatetax1());
		System.out.println(" getPinaltyfee1 : "+ 	plb.getPinaltyfee1());
		System.out.println(" getSlalwbp1 : "+ 	plb.getSlalwbp1());
		System.out.println(" getSahlwbp1 : "+ 	plb.getSahlwbp1());
		System.out.println(" getSlawbp1 : "+ 	plb.getSlawbp1());
		System.out.println(" getSahwbp1 : "+ 	plb.getSahwbp1());
		System.out.println(" getSlakvarh1 : "+ 	plb.getSlakvarh1());
		System.out.println(" getSahkvarh1 : "+ 	plb.getSahkvarh1());
		System.out.println(" getBlth2 : "+ 	plb.getBlth2());
		System.out.println(" getDuedate2 : "+ 	plb.getDuedate2());
		System.out.println(" getMeterreaddate2 : "+ 	plb.getMeterreaddate2());
		System.out.println(" getRptag2 : "+ 	plb.getRptag2());
		System.out.println(" getIncentive2 : "+ 	plb.getIncentive2());
		System.out.println(" getValuedatetax2 : "+ 	plb.getValuedatetax2());
		System.out.println(" getPinaltyfee2 : "+ 	plb.getPinaltyfee2());
		System.out.println(" getSlalwbp2 : "+ 	plb.getSlalwbp2());
		System.out.println(" getSahlwbp2 : "+ 	plb.getSahlwbp2());
		System.out.println(" getSlawbp2 : "+ 	plb.getSlawbp2());
		System.out.println(" getSahwbp2 : "+ 	plb.getSahwbp2());
		System.out.println(" getSlakvarh2 : "+ 	plb.getSlakvarh2());
		System.out.println(" getSahkvarh2 : "+ 	plb.getSahkvarh2());
		System.out.println(" getBlth3 : "+ 	plb.getBlth3());
		System.out.println(" getDuedate3 : "+ 	plb.getDuedate3());
		System.out.println(" getMeterreaddate3 : "+ 	plb.getMeterreaddate3());
		System.out.println(" getRptag3 : "+ 	plb.getRptag3());
		System.out.println(" getIncentive3 : "+ 	plb.getIncentive3());
		System.out.println(" getValuedatetax3 : "+ 	plb.getValuedatetax3());
		System.out.println(" getPinaltyfee3 : "+ 	plb.getPinaltyfee3());
		System.out.println(" getSlalwbp3 : "+ 	plb.getSlalwbp3());
		System.out.println(" getSahlwbp3 : "+ 	plb.getSahlwbp3());
		System.out.println(" getSlawbp3 : "+ 	plb.getSlawbp3());
		System.out.println(" getSahwbp3 : "+ 	plb.getSahwbp3());
		System.out.println(" getSlakvarh3 : "+ 	plb.getSlakvarh3());
		System.out.println(" getSahkvarh3 : "+ 	plb.getSahkvarh3());
		System.out.println(" getBlth4 : "+ 	plb.getBlth4());
		System.out.println(" getDuedate4 : "+ 	plb.getDuedate4());
		System.out.println(" getMeterreaddate4 : "+ 	plb.getMeterreaddate4());
		System.out.println(" getRptag4 : "+ 	plb.getRptag4());
		System.out.println(" getIncentive4 : "+ 	plb.getIncentive4());
		System.out.println(" getValuedatetax4 : "+ 	plb.getValuedatetax4());
		System.out.println(" getPinaltyfee4 : "+ 	plb.getPinaltyfee4());
		System.out.println(" getSlalwbp4 : "+ 	plb.getSlalwbp4());
		System.out.println(" getSahlwbp4 : "+ 	plb.getSahlwbp4());
		System.out.println(" getSlawbp4 : "+ 	plb.getSlawbp4());
		System.out.println(" getSahwbp4 : "+ 	plb.getSahwbp4());
		System.out.println(" getSlakvarh4 : "+ 	plb.getSlakvarh4());
		System.out.println(" getSahkvarh4 : "+ 	plb.getSahkvarh4());
		System.out.println(" getAlamat : "+ 	plb.getAlamat());
		System.out.println(" getPlnnpwp : "+ 	plb.getPlnnpwp());
		System.out.println(" getSubscribernpwp : "+ 	plb.getSubscribernpwp());
		System.out.println(" getTotalrpgtag : "+ 	plb.getTotalrpgtag());
		System.out.println(" getInfoteks : "+ 	plb.getInfoteks());
		return plb;
	}
	
	public static void reqPLNPascaBayar(Payment payment){
		System.out.println("\n\n\nPLNPascaBayar .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("PLNPASC");
		PLNPascaBayar plb = rp.getRequestBean(payment);
		System.out.println(" getKodeproduk : "+ 	plb.getKodeproduk());
		System.out.println(" getWaktu : "+ 	plb.getWaktu());
		System.out.println(" getIdpelanggan1 : "+ 	plb.getIdpelanggan1());
		System.out.println(" getIdpelanggan2 : "+ 	plb.getIdpelanggan2());
		System.out.println(" getIdpelanggan3 : "+ 	plb.getIdpelanggan3());
		System.out.println(" getNominal : "+ 	plb.getNominal());
		System.out.println(" getBiayaadmin : "+ 	plb.getBiayaadmin());
		System.out.println(" getUid : "+ 	plb.getUid());
		System.out.println(" getPin : "+ 	plb.getPin());
		System.out.println(" getRef1 : "+ 	plb.getRef1());
		System.out.println(" getRef2 : "+ 	plb.getRef2());
		System.out.println(" getRef3 : "+ 	plb.getRef3());
		System.out.println(" getStatus : "+ 	plb.getStatus());
		System.out.println(" getKeterangan : "+ 	plb.getKeterangan());
		System.out.println(" getSwitcherId : "+ 	plb.getSwitcherId());
		System.out.println(" getSubscriberId : "+ 	plb.getSubscriberId());
		System.out.println(" getBillstatus : "+ 	plb.getBillstatus());
		System.out.println(" getPaymentstatus : "+ 	plb.getPaymentstatus());
		System.out.println(" getTotaloutstandingbell : "+ 	plb.getTotaloutstandingbell());
		System.out.println(" getSwereferencenumber : "+ 	plb.getSwereferencenumber());
		System.out.println(" getSubscribename : "+ 	plb.getSubscribename());
		System.out.println(" getServiceunit : "+ 	plb.getServiceunit());
		System.out.println(" getServiceunitphone : "+ 	plb.getServiceunitphone());
		System.out.println(" getSubscribeSegmentation : "+ 	plb.getSubscribeSegmentation());
		System.out.println(" getPowerconsumingcategory : "+ 	plb.getPowerconsumingcategory());
		System.out.println(" getTotaladmincharge : "+ 	plb.getTotaladmincharge());
		System.out.println(" getBlth1 : "+ 	plb.getBlth1());
		System.out.println(" getDuedate1 : "+ 	plb.getDuedate1());
		System.out.println(" getMeterreaddate1 : "+ 	plb.getMeterreaddate1());
		System.out.println(" getRptag1 : "+ 	plb.getRptag1());
		System.out.println(" getIncentive1 : "+ 	plb.getIncentive1());
		System.out.println(" getValuedatetax1 : "+ 	plb.getValuedatetax1());
		System.out.println(" getPinaltyfee1 : "+ 	plb.getPinaltyfee1());
		System.out.println(" getSlalwbp1 : "+ 	plb.getSlalwbp1());
		System.out.println(" getSahlwbp1 : "+ 	plb.getSahlwbp1());
		System.out.println(" getSlawbp1 : "+ 	plb.getSlawbp1());
		System.out.println(" getSahwbp1 : "+ 	plb.getSahwbp1());
		System.out.println(" getSlakvarh1 : "+ 	plb.getSlakvarh1());
		System.out.println(" getSahkvarh1 : "+ 	plb.getSahkvarh1());
		System.out.println(" getBlth2 : "+ 	plb.getBlth2());
		System.out.println(" getDuedate2 : "+ 	plb.getDuedate2());
		System.out.println(" getMeterreaddate2 : "+ 	plb.getMeterreaddate2());
		System.out.println(" getRptag2 : "+ 	plb.getRptag2());
		System.out.println(" getIncentive2 : "+ 	plb.getIncentive2());
		System.out.println(" getValuedatetax2 : "+ 	plb.getValuedatetax2());
		System.out.println(" getPinaltyfee2 : "+ 	plb.getPinaltyfee2());
		System.out.println(" getSlalwbp2 : "+ 	plb.getSlalwbp2());
		System.out.println(" getSahlwbp2 : "+ 	plb.getSahlwbp2());
		System.out.println(" getSlawbp2 : "+ 	plb.getSlawbp2());
		System.out.println(" getSahwbp2 : "+ 	plb.getSahwbp2());
		System.out.println(" getSlakvarh2 : "+ 	plb.getSlakvarh2());
		System.out.println(" getSahkvarh2 : "+ 	plb.getSahkvarh2());
		System.out.println(" getBlth3 : "+ 	plb.getBlth3());
		System.out.println(" getDuedate3 : "+ 	plb.getDuedate3());
		System.out.println(" getMeterreaddate3 : "+ 	plb.getMeterreaddate3());
		System.out.println(" getRptag3 : "+ 	plb.getRptag3());
		System.out.println(" getIncentive3 : "+ 	plb.getIncentive3());
		System.out.println(" getValuedatetax3 : "+ 	plb.getValuedatetax3());
		System.out.println(" getPinaltyfee3 : "+ 	plb.getPinaltyfee3());
		System.out.println(" getSlalwbp3 : "+ 	plb.getSlalwbp3());
		System.out.println(" getSahlwbp3 : "+ 	plb.getSahlwbp3());
		System.out.println(" getSlawbp3 : "+ 	plb.getSlawbp3());
		System.out.println(" getSahwbp3 : "+ 	plb.getSahwbp3());
		System.out.println(" getSlakvarh3 : "+ 	plb.getSlakvarh3());
		System.out.println(" getSahkvarh3 : "+ 	plb.getSahkvarh3());
		System.out.println(" getBlth4 : "+ 	plb.getBlth4());
		System.out.println(" getDuedate4 : "+ 	plb.getDuedate4());
		System.out.println(" getMeterreaddate4 : "+ 	plb.getMeterreaddate4());
		System.out.println(" getRptag4 : "+ 	plb.getRptag4());
		System.out.println(" getIncentive4 : "+ 	plb.getIncentive4());
		System.out.println(" getValuedatetax4 : "+ 	plb.getValuedatetax4());
		System.out.println(" getPinaltyfee4 : "+ 	plb.getPinaltyfee4());
		System.out.println(" getSlalwbp4 : "+ 	plb.getSlalwbp4());
		System.out.println(" getSahlwbp4 : "+ 	plb.getSahlwbp4());
		System.out.println(" getSlawbp4 : "+ 	plb.getSlawbp4());
		System.out.println(" getSahwbp4 : "+ 	plb.getSahwbp4());
		System.out.println(" getSlakvarh4 : "+ 	plb.getSlakvarh4());
		System.out.println(" getSahkvarh4 : "+ 	plb.getSahkvarh4());
		System.out.println(" getAlamat : "+ 	plb.getAlamat());
		System.out.println(" getPlnnpwp : "+ 	plb.getPlnnpwp());
		System.out.println(" getSubscribernpwp : "+ 	plb.getSubscribernpwp());
		System.out.println(" getTotalrpgtag : "+ 	plb.getTotalrpgtag());
		System.out.println(" getInfoteks : "+ 	plb.getInfoteks());
	}
	
	public static PLNPascaBayar reqPLNPraBayar(Inquery inquery){
		System.out.println("\n\n\nPLNPraBayarInquery .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setKodeProduk("PLNPRA");
		PLNPascaBayar plb = rp.getPLNPascaBayarRespone(inquery);
		System.out.println(" getKodeproduk : "+ 	plb.getKodeproduk());
		System.out.println(" getWaktu : "+ 	plb.getWaktu());
		System.out.println(" getIdpelanggan1 : "+ 	plb.getIdpelanggan1());
		System.out.println(" getIdpelanggan2 : "+ 	plb.getIdpelanggan2());
		System.out.println(" getIdpelanggan3 : "+ 	plb.getIdpelanggan3());
		System.out.println(" getNominal : "+ 	plb.getNominal());
		System.out.println(" getBiayaadmin : "+ 	plb.getBiayaadmin());
		System.out.println(" getUid : "+ 	plb.getUid());
		System.out.println(" getPin : "+ 	plb.getPin());
		System.out.println(" getRef1 : "+ 	plb.getRef1());
		System.out.println(" getRef2 : "+ 	plb.getRef2());
		System.out.println(" getRef3 : "+ 	plb.getRef3());
		System.out.println(" getStatus : "+ 	plb.getStatus());
		System.out.println(" getKeterangan : "+ 	plb.getKeterangan());
		System.out.println(" getSwitcherId : "+ 	plb.getSwitcherId());
		System.out.println(" getSubscriberId : "+ 	plb.getSubscriberId());
		System.out.println(" getBillstatus : "+ 	plb.getBillstatus());
		System.out.println(" getPaymentstatus : "+ 	plb.getPaymentstatus());
		System.out.println(" getTotaloutstandingbell : "+ 	plb.getTotaloutstandingbell());
		System.out.println(" getSwereferencenumber : "+ 	plb.getSwereferencenumber());
		System.out.println(" getSubscribename : "+ 	plb.getSubscribename());
		System.out.println(" getServiceunit : "+ 	plb.getServiceunit());
		System.out.println(" getServiceunitphone : "+ 	plb.getServiceunitphone());
		System.out.println(" getSubscribeSegmentation : "+ 	plb.getSubscribeSegmentation());
		System.out.println(" getPowerconsumingcategory : "+ 	plb.getPowerconsumingcategory());
		System.out.println(" getTotaladmincharge : "+ 	plb.getTotaladmincharge());
		System.out.println(" getBlth1 : "+ 	plb.getBlth1());
		System.out.println(" getDuedate1 : "+ 	plb.getDuedate1());
		System.out.println(" getMeterreaddate1 : "+ 	plb.getMeterreaddate1());
		System.out.println(" getRptag1 : "+ 	plb.getRptag1());
		System.out.println(" getIncentive1 : "+ 	plb.getIncentive1());
		System.out.println(" getValuedatetax1 : "+ 	plb.getValuedatetax1());
		System.out.println(" getPinaltyfee1 : "+ 	plb.getPinaltyfee1());
		System.out.println(" getSlalwbp1 : "+ 	plb.getSlalwbp1());
		System.out.println(" getSahlwbp1 : "+ 	plb.getSahlwbp1());
		System.out.println(" getSlawbp1 : "+ 	plb.getSlawbp1());
		System.out.println(" getSahwbp1 : "+ 	plb.getSahwbp1());
		System.out.println(" getSlakvarh1 : "+ 	plb.getSlakvarh1());
		System.out.println(" getSahkvarh1 : "+ 	plb.getSahkvarh1());
		System.out.println(" getBlth2 : "+ 	plb.getBlth2());
		System.out.println(" getDuedate2 : "+ 	plb.getDuedate2());
		System.out.println(" getMeterreaddate2 : "+ 	plb.getMeterreaddate2());
		System.out.println(" getRptag2 : "+ 	plb.getRptag2());
		System.out.println(" getIncentive2 : "+ 	plb.getIncentive2());
		System.out.println(" getValuedatetax2 : "+ 	plb.getValuedatetax2());
		System.out.println(" getPinaltyfee2 : "+ 	plb.getPinaltyfee2());
		System.out.println(" getSlalwbp2 : "+ 	plb.getSlalwbp2());
		System.out.println(" getSahlwbp2 : "+ 	plb.getSahlwbp2());
		System.out.println(" getSlawbp2 : "+ 	plb.getSlawbp2());
		System.out.println(" getSahwbp2 : "+ 	plb.getSahwbp2());
		System.out.println(" getSlakvarh2 : "+ 	plb.getSlakvarh2());
		System.out.println(" getSahkvarh2 : "+ 	plb.getSahkvarh2());
		System.out.println(" getBlth3 : "+ 	plb.getBlth3());
		System.out.println(" getDuedate3 : "+ 	plb.getDuedate3());
		System.out.println(" getMeterreaddate3 : "+ 	plb.getMeterreaddate3());
		System.out.println(" getRptag3 : "+ 	plb.getRptag3());
		System.out.println(" getIncentive3 : "+ 	plb.getIncentive3());
		System.out.println(" getValuedatetax3 : "+ 	plb.getValuedatetax3());
		System.out.println(" getPinaltyfee3 : "+ 	plb.getPinaltyfee3());
		System.out.println(" getSlalwbp3 : "+ 	plb.getSlalwbp3());
		System.out.println(" getSahlwbp3 : "+ 	plb.getSahlwbp3());
		System.out.println(" getSlawbp3 : "+ 	plb.getSlawbp3());
		System.out.println(" getSahwbp3 : "+ 	plb.getSahwbp3());
		System.out.println(" getSlakvarh3 : "+ 	plb.getSlakvarh3());
		System.out.println(" getSahkvarh3 : "+ 	plb.getSahkvarh3());
		System.out.println(" getBlth4 : "+ 	plb.getBlth4());
		System.out.println(" getDuedate4 : "+ 	plb.getDuedate4());
		System.out.println(" getMeterreaddate4 : "+ 	plb.getMeterreaddate4());
		System.out.println(" getRptag4 : "+ 	plb.getRptag4());
		System.out.println(" getIncentive4 : "+ 	plb.getIncentive4());
		System.out.println(" getValuedatetax4 : "+ 	plb.getValuedatetax4());
		System.out.println(" getPinaltyfee4 : "+ 	plb.getPinaltyfee4());
		System.out.println(" getSlalwbp4 : "+ 	plb.getSlalwbp4());
		System.out.println(" getSahlwbp4 : "+ 	plb.getSahlwbp4());
		System.out.println(" getSlawbp4 : "+ 	plb.getSlawbp4());
		System.out.println(" getSahwbp4 : "+ 	plb.getSahwbp4());
		System.out.println(" getSlakvarh4 : "+ 	plb.getSlakvarh4());
		System.out.println(" getSahkvarh4 : "+ 	plb.getSahkvarh4());
		System.out.println(" getAlamat : "+ 	plb.getAlamat());
		System.out.println(" getPlnnpwp : "+ 	plb.getPlnnpwp());
		System.out.println(" getSubscribernpwp : "+ 	plb.getSubscribernpwp());
		System.out.println(" getTotalrpgtag : "+ 	plb.getTotalrpgtag());
		System.out.println(" getInfoteks : "+ 	plb.getInfoteks());
		return plb;
	}
	
	public static PLNPascaBayar reqPLNPraBayar(Payment payment){
		System.out.println("\n\n\nPLNPraBayarPayment .....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("PLNPRA");
		PLNPascaBayar plb = rp.getRequestBean(payment);
		System.out.println(" getKodeproduk : "+ 	plb.getKodeproduk());
		System.out.println(" getWaktu : "+ 	plb.getWaktu());
		System.out.println(" getIdpelanggan1 : "+ 	plb.getIdpelanggan1());
		System.out.println(" getIdpelanggan2 : "+ 	plb.getIdpelanggan2());
		System.out.println(" getIdpelanggan3 : "+ 	plb.getIdpelanggan3());
		System.out.println(" getNominal : "+ 	plb.getNominal());
		System.out.println(" getBiayaadmin : "+ 	plb.getBiayaadmin());
		System.out.println(" getUid : "+ 	plb.getUid());
		System.out.println(" getPin : "+ 	plb.getPin());
		System.out.println(" getRef1 : "+ 	plb.getRef1());
		System.out.println(" getRef2 : "+ 	plb.getRef2());
		System.out.println(" getRef3 : "+ 	plb.getRef3());
		System.out.println(" getStatus : "+ 	plb.getStatus());
		System.out.println(" getKeterangan : "+ 	plb.getKeterangan());
		System.out.println(" getSwitcherId : "+ 	plb.getSwitcherId());
		System.out.println(" getSubscriberId : "+ 	plb.getSubscriberId());
		System.out.println(" getBillstatus : "+ 	plb.getBillstatus());
		System.out.println(" getPaymentstatus : "+ 	plb.getPaymentstatus());
		System.out.println(" getTotaloutstandingbell : "+ 	plb.getTotaloutstandingbell());
		System.out.println(" getSwereferencenumber : "+ 	plb.getSwereferencenumber());
		System.out.println(" getSubscribename : "+ 	plb.getSubscribename());
		System.out.println(" getServiceunit : "+ 	plb.getServiceunit());
		System.out.println(" getServiceunitphone : "+ 	plb.getServiceunitphone());
		System.out.println(" getSubscribeSegmentation : "+ 	plb.getSubscribeSegmentation());
		System.out.println(" getPowerconsumingcategory : "+ 	plb.getPowerconsumingcategory());
		System.out.println(" getTotaladmincharge : "+ 	plb.getTotaladmincharge());
		System.out.println(" getBlth1 : "+ 	plb.getBlth1());
		System.out.println(" getDuedate1 : "+ 	plb.getDuedate1());
		System.out.println(" getMeterreaddate1 : "+ 	plb.getMeterreaddate1());
		System.out.println(" getRptag1 : "+ 	plb.getRptag1());
		System.out.println(" getIncentive1 : "+ 	plb.getIncentive1());
		System.out.println(" getValuedatetax1 : "+ 	plb.getValuedatetax1());
		System.out.println(" getPinaltyfee1 : "+ 	plb.getPinaltyfee1());
		System.out.println(" getSlalwbp1 : "+ 	plb.getSlalwbp1());
		System.out.println(" getSahlwbp1 : "+ 	plb.getSahlwbp1());
		System.out.println(" getSlawbp1 : "+ 	plb.getSlawbp1());
		System.out.println(" getSahwbp1 : "+ 	plb.getSahwbp1());
		System.out.println(" getSlakvarh1 : "+ 	plb.getSlakvarh1());
		System.out.println(" getSahkvarh1 : "+ 	plb.getSahkvarh1());
		System.out.println(" getBlth2 : "+ 	plb.getBlth2());
		System.out.println(" getDuedate2 : "+ 	plb.getDuedate2());
		System.out.println(" getMeterreaddate2 : "+ 	plb.getMeterreaddate2());
		System.out.println(" getRptag2 : "+ 	plb.getRptag2());
		System.out.println(" getIncentive2 : "+ 	plb.getIncentive2());
		System.out.println(" getValuedatetax2 : "+ 	plb.getValuedatetax2());
		System.out.println(" getPinaltyfee2 : "+ 	plb.getPinaltyfee2());
		System.out.println(" getSlalwbp2 : "+ 	plb.getSlalwbp2());
		System.out.println(" getSahlwbp2 : "+ 	plb.getSahlwbp2());
		System.out.println(" getSlawbp2 : "+ 	plb.getSlawbp2());
		System.out.println(" getSahwbp2 : "+ 	plb.getSahwbp2());
		System.out.println(" getSlakvarh2 : "+ 	plb.getSlakvarh2());
		System.out.println(" getSahkvarh2 : "+ 	plb.getSahkvarh2());
		System.out.println(" getBlth3 : "+ 	plb.getBlth3());
		System.out.println(" getDuedate3 : "+ 	plb.getDuedate3());
		System.out.println(" getMeterreaddate3 : "+ 	plb.getMeterreaddate3());
		System.out.println(" getRptag3 : "+ 	plb.getRptag3());
		System.out.println(" getIncentive3 : "+ 	plb.getIncentive3());
		System.out.println(" getValuedatetax3 : "+ 	plb.getValuedatetax3());
		System.out.println(" getPinaltyfee3 : "+ 	plb.getPinaltyfee3());
		System.out.println(" getSlalwbp3 : "+ 	plb.getSlalwbp3());
		System.out.println(" getSahlwbp3 : "+ 	plb.getSahlwbp3());
		System.out.println(" getSlawbp3 : "+ 	plb.getSlawbp3());
		System.out.println(" getSahwbp3 : "+ 	plb.getSahwbp3());
		System.out.println(" getSlakvarh3 : "+ 	plb.getSlakvarh3());
		System.out.println(" getSahkvarh3 : "+ 	plb.getSahkvarh3());
		System.out.println(" getBlth4 : "+ 	plb.getBlth4());
		System.out.println(" getDuedate4 : "+ 	plb.getDuedate4());
		System.out.println(" getMeterreaddate4 : "+ 	plb.getMeterreaddate4());
		System.out.println(" getRptag4 : "+ 	plb.getRptag4());
		System.out.println(" getIncentive4 : "+ 	plb.getIncentive4());
		System.out.println(" getValuedatetax4 : "+ 	plb.getValuedatetax4());
		System.out.println(" getPinaltyfee4 : "+ 	plb.getPinaltyfee4());
		System.out.println(" getSlalwbp4 : "+ 	plb.getSlalwbp4());
		System.out.println(" getSahlwbp4 : "+ 	plb.getSahlwbp4());
		System.out.println(" getSlawbp4 : "+ 	plb.getSlawbp4());
		System.out.println(" getSahwbp4 : "+ 	plb.getSahwbp4());
		System.out.println(" getSlakvarh4 : "+ 	plb.getSlakvarh4());
		System.out.println(" getSahkvarh4 : "+ 	plb.getSahkvarh4());
		System.out.println(" getAlamat : "+ 	plb.getAlamat());
		System.out.println(" getPlnnpwp : "+ 	plb.getPlnnpwp());
		System.out.println(" getSubscribernpwp : "+ 	plb.getSubscribernpwp());
		System.out.println(" getTotalrpgtag : "+ 	plb.getTotalrpgtag());
		System.out.println(" getInfoteks : "+ 	plb.getInfoteks());
		return plb;
	}
	
	public static void reqPulsaRespone(){
		System.out.println("\n\n\nPulsaRespone ....\n\n\n");
		RequestBeans service = new RequestBeans();
		Pulsa pulsa = new Pulsa();
		pulsa.setKodeproduk("S50H");
		//pulsa.setKodeproduk("I50H");
		//pulsa.setKodeproduk("XR25H");
		//pulsa.setKodeproduk("T50H");
		//pulsa.setKodeproduk("CM50H");
		//pulsa.setNohp("081270209315");
		//pulsa.setNohp("081218064704");//floodtsel1  
		//pulsa.setNohp("081235180899");//kipruk
		//pulsa.setNohp("081218119552");//mbashanti
		//pulsa.setNohp("081319550173");//mas bayu
		//pulsa.setNohp("089516676172");//tia
		//pulsa.setNohp("085778071731");//DESTA
		//pulsa.setNohp("085716393170");//sifa
		//pulsa.setNohp("085959831762");//floodxl1
		//pulsa.setNohp("081807366329");
		//pulsa.setNohp("08999038342");//anie
		//pulsa.setNohp("081218943269");//mbadian
		pulsa.setNohp("081295910296");
		//pulsa.setNohp("087854033229");
		//pulsa.setNohp("08881676353");//smartfren inet resza
		//pulsa.setNohp("081353607339");//blek
		//pulsa.setKodeproduk("S50H");
		//pulsa.setNohp("081295910296");
		pulsa.setPin("990632");
		//pulsa.setRef1("3990");
		pulsa.setUid("AP45601");
		PulsaRespone pulsaRes = service.getPulsaRespone(pulsa);
		System.out.println(" Keterangan : "+	pulsaRes.getKeterangan());
		System.out.println(" KodeProduksi : "+	pulsaRes.getKodeProduksi());
		System.out.println(" Nohp : "+	pulsaRes.getNohp());
		System.out.println(" Pin : "+	pulsaRes.getPin());
		System.out.println(" Ref1 : "+	pulsaRes.getRef1());
		System.out.println(" Ref2 : "+	pulsaRes.getRef2());
		System.out.println(" Sn : "+	pulsaRes.getSn());
		System.out.println(" Status : "+	pulsaRes.getStatus());
		System.out.println(" UID : "+	pulsaRes.getUID());
		System.out.println(" Waktu : "+	pulsaRes.getWaktu());

	}
	public static TelkomGroup reqTelkomGroup(Inquery inquery){
		System.out.println("\n\n\nTelkomGroupInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		//inquery.setKodeProduk("TVTLKMV");
		TelkomGroup tg = rp.getTelkomGroupRespone(inquery);
		if(tg!=null){
		System.out.println(" 	getBiayaadmin()	: "+	tg.getBiayaadmin()	);
		System.out.println(" 	getIdpelanggan1()	: "+	tg.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	tg.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	tg.getIdpelanggan3()	);
		System.out.println(" 	getJumlahbill()	: "+	tg.getJumlahbill()	);
		System.out.println(" 	getKeterangan()	: "+	tg.getKeterangan()	);
		System.out.println(" 	getKodearea()	: "+	tg.getKodearea()	);
		System.out.println(" 	getKodedatel()	: "+	tg.getKodedatel()	);
		System.out.println(" 	getKodedivre()	: "+	tg.getKodedivre()	);
		System.out.println(" 	getKodeproduk()	: "+	tg.getKodeproduk()	);
		System.out.println(" 	getNamapelanggan()	: "+	tg.getNamapelanggan()	);
		System.out.println(" 	getNilaitagihan1()	: "+	tg.getNilaitagihan1()	);
		System.out.println(" 	getNilaitagihan2()	: "+	tg.getNilaitagihan2()	);
		System.out.println(" 	getNilaitagihan3()	: "+	tg.getNilaitagihan3()	);
		System.out.println(" 	getNominal()	: "+	tg.getNominal()	);
		System.out.println(" 	getNomorreferensi1()	: "+	tg.getNomorreferensi1()	);
		System.out.println(" 	getNomorreferensi2()	: "+	tg.getNomorreferensi2()	);
		System.out.println(" 	getNomorreferensi3()	: "+	tg.getNomorreferensi3()	);
		System.out.println(" 	getNomortelepon()	: "+	tg.getNomortelepon()	);
		System.out.println(" 	getNpwp()	: "+	tg.getNpwp()	);
		System.out.println(" 	getPin()	: "+	tg.getPin()	);
		System.out.println(" 	getRef1()	: "+	tg.getRef1()	);
		System.out.println(" 	getRef2()	: "+	tg.getRef2()	);
		System.out.println(" 	getRef3()	: "+	tg.getRef3()	);
		System.out.println(" 	getStatus()	: "+	tg.getStatus()	);
		System.out.println(" 	getUid()	: "+	tg.getUid()	);
		System.out.println(" 	getWaktu()	: "+	tg.getWaktu()	);
		}else{
			System.out.println("TelkomGroup NULL");
		}
		return tg;
	}
	public static TelkomGroup reqTelkomGroup(Payment payment){
		System.out.println("\n\n\nTelkomGroupInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("SPEEDY");
		TelkomGroup tg = rp.getTelkomGroupRespone(payment);
		System.out.println(" 	getBiayaadmin()	: "+	tg.getBiayaadmin()	);
		System.out.println(" 	getIdpelanggan1()	: "+	tg.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	tg.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	tg.getIdpelanggan3()	);
		System.out.println(" 	getJumlahbill()	: "+	tg.getJumlahbill()	);
		System.out.println(" 	getKeterangan()	: "+	tg.getKeterangan()	);
		System.out.println(" 	getKodearea()	: "+	tg.getKodearea()	);
		System.out.println(" 	getKodedatel()	: "+	tg.getKodedatel()	);
		System.out.println(" 	getKodedivre()	: "+	tg.getKodedivre()	);
		System.out.println(" 	getKodeproduk()	: "+	tg.getKodeproduk()	);
		System.out.println(" 	getNamapelanggan()	: "+	tg.getNamapelanggan()	);
		System.out.println(" 	getNilaitagihan1()	: "+	tg.getNilaitagihan1()	);
		System.out.println(" 	getNilaitagihan2()	: "+	tg.getNilaitagihan2()	);
		System.out.println(" 	getNilaitagihan3()	: "+	tg.getNilaitagihan3()	);
		System.out.println(" 	getNominal()	: "+	tg.getNominal()	);
		System.out.println(" 	getNomorreferensi1()	: "+	tg.getNomorreferensi1()	);
		System.out.println(" 	getNomorreferensi2()	: "+	tg.getNomorreferensi2()	);
		System.out.println(" 	getNomorreferensi3()	: "+	tg.getNomorreferensi3()	);
		System.out.println(" 	getNomortelepon()	: "+	tg.getNomortelepon()	);
		System.out.println(" 	getNpwp()	: "+	tg.getNpwp()	);
		System.out.println(" 	getPin()	: "+	tg.getPin()	);
		System.out.println(" 	getRef1()	: "+	tg.getRef1()	);
		System.out.println(" 	getRef2()	: "+	tg.getRef2()	);
		System.out.println(" 	getRef3()	: "+	tg.getRef3()	);
		System.out.println(" 	getStatus()	: "+	tg.getStatus()	);
		System.out.println(" 	getUid()	: "+	tg.getUid()	);
		System.out.println(" 	getWaktu()	: "+	tg.getWaktu()	);
		return tg;
	}
	public static TelPascaBayar reqTelPascaBayar(Inquery inquery){
		System.out.println("\n\n\nTelPascaBayarInquery ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		//inquery.setKodeProduk("TELEPON");
		TelPascaBayar tpb = rp.getTelPascaBayarRespone(inquery);
		System.out.println(" 	getBiayaadmin()	: "+	tpb.getBiayaadmin()	);
		System.out.println(" 	getIdpelanggan1()	: "+	tpb.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	tpb.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	tpb.getIdpelanggan3()	);
		System.out.println(" 	getJumlahbill()	: "+	tpb.getJumlahbill()	);
		System.out.println(" 	getKeterangan()	: "+	tpb.getKeterangan()	);
		System.out.println(" 	getKodearea()	: "+	tpb.getKodearea()	);
		System.out.println(" 	getKodedatel()	: "+	tpb.getKodedatel()	);
		System.out.println(" 	getKodedivre()	: "+	tpb.getKodedivre()	);
		System.out.println(" 	getKodeproduk()	: "+	tpb.getKodeProduk()	);
		System.out.println(" 	getNamapelanggan()	: "+	tpb.getNamapelanggan()	);
		System.out.println(" 	getNilaitagihan1()	: "+	tpb.getNilaitagihan1()	);
		System.out.println(" 	getNilaitagihan2()	: "+	tpb.getNilaitagihan2()	);
		System.out.println(" 	getNilaitagihan3()	: "+	tpb.getNilaitagihan3()	);
		System.out.println(" 	getNominal()	: "+	tpb.getNominal()	);
		System.out.println(" 	getNomorreferensi1()	: "+	tpb.getNomorreferensi1()	);
		System.out.println(" 	getNomorreferensi2()	: "+	tpb.getNomorreferensi2()	);
		System.out.println(" 	getNomorreferensi3()	: "+	tpb.getNomorreferensi3()	);
		System.out.println(" 	getNomortelepon()	: "+	tpb.getNomortelepon()	);
		System.out.println(" 	getNpwp()	: "+	tpb.getNpwp()	);
		System.out.println(" 	getPin()	: "+	tpb.getPin()	);
		System.out.println(" 	getRef1()	: "+	tpb.getRef1()	);
		System.out.println(" 	getRef2()	: "+	tpb.getRef2()	);
		System.out.println(" 	getRef3()	: "+	tpb.getRef3()	);
		System.out.println(" 	getStatus()	: "+	tpb.getStatus()	);
		System.out.println(" 	getUid()	: "+	tpb.getUID()	);
		System.out.println(" 	getWaktu()	: "+	tpb.getWaktu()	);
		return tpb;
	}
	public static TelPascaBayar reqTelPascaBayar(Payment payment){
		System.out.println("\n\n\nTelPascaBayar ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("TELEPON");
		TelPascaBayar tpb = rp.getTelPascaBayarRespone(payment);
		System.out.println(" 	getBiayaadmin()	: "+	tpb.getBiayaadmin()	);
		System.out.println(" 	getIdpelanggan1()	: "+	tpb.getIdpelanggan1()	);
		System.out.println(" 	getIdpelanggan2()	: "+	tpb.getIdpelanggan2()	);
		System.out.println(" 	getIdpelanggan3()	: "+	tpb.getIdpelanggan3()	);
		System.out.println(" 	getJumlahbill()	: "+	tpb.getJumlahbill()	);
		System.out.println(" 	getKeterangan()	: "+	tpb.getKeterangan()	);
		System.out.println(" 	getKodearea()	: "+	tpb.getKodearea()	);
		System.out.println(" 	getKodedatel()	: "+	tpb.getKodedatel()	);
		System.out.println(" 	getKodedivre()	: "+	tpb.getKodedivre()	);
		System.out.println(" 	getKodeproduk()	: "+	tpb.getKodeProduk()	);
		System.out.println(" 	getNamapelanggan()	: "+	tpb.getNamapelanggan()	);
		System.out.println(" 	getNilaitagihan1()	: "+	tpb.getNilaitagihan1()	);
		System.out.println(" 	getNilaitagihan2()	: "+	tpb.getNilaitagihan2()	);
		System.out.println(" 	getNilaitagihan3()	: "+	tpb.getNilaitagihan3()	);
		System.out.println(" 	getNominal()	: "+	tpb.getNominal()	);
		System.out.println(" 	getNomorreferensi1()	: "+	tpb.getNomorreferensi1()	);
		System.out.println(" 	getNomorreferensi2()	: "+	tpb.getNomorreferensi2()	);
		System.out.println(" 	getNomorreferensi3()	: "+	tpb.getNomorreferensi3()	);
		System.out.println(" 	getNomortelepon()	: "+	tpb.getNomortelepon()	);
		System.out.println(" 	getNpwp()	: "+	tpb.getNpwp()	);
		System.out.println(" 	getPin()	: "+	tpb.getPin()	);
		System.out.println(" 	getRef1()	: "+	tpb.getRef1()	);
		System.out.println(" 	getRef2()	: "+	tpb.getRef2()	);
		System.out.println(" 	getRef3()	: "+	tpb.getRef3()	);
		System.out.println(" 	getStatus()	: "+	tpb.getStatus()	);
		System.out.println(" 	getUid()	: "+	tpb.getUID()	);
		System.out.println(" 	getWaktu()	: "+	tpb.getWaktu()	);
		return tpb;
	}
	public static TVKabel reqTVKabel(Inquery inquery){
		System.out.println("\n\n\nTVKabel ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		inquery.setKodeProduk("TVAORA");
		TVKabel tk = rp.getTVkabelRespone(inquery);
		System.out.println(" 	tk.getAdmincharge()	: "+	tk.getAdmincharge()	);
		System.out.println(" 	tk.getBiayaadmin()	: "+	tk.getBiayaadmin()	);
		System.out.println(" 	tk.getBillamount()	: "+	tk.getBillamount()	);
		System.out.println(" 	tk.getBilleradminfee()	: "+	tk.getBilleradminfee()	);
		System.out.println(" 	tk.getBillercode()	: "+	tk.getBillercode()	);
		System.out.println(" 	tk.getBillerrefnumber()	: "+	tk.getBillerrefnumber()	);
		System.out.println(" 	tk.getBillquantity()	: "+	tk.getBillquantity()	);
		System.out.println(" 	tk.getCustomeinfo1()	: "+	tk.getCustomeinfo1()	);
		System.out.println(" 	tk.getCustomeinfo2()	: "+	tk.getCustomeinfo2()	);
		System.out.println(" 	tk.getCustomeinfo3()	: "+	tk.getCustomeinfo3()	);
		System.out.println(" 	tk.getCustomeraddress()	: "+	tk.getCustomeraddress()	);
		System.out.println(" 	tk.getCustomerId()	: "+	tk.getCustomerId()	);
		System.out.println(" 	tk.getCustomerName()	: "+	tk.getCustomerName()	);
		System.out.println(" 	tk.getDuedate()	: "+	tk.getDuedate()	);
		System.out.println(" 	tk.getIdpelanggan1()	: "+	tk.getIdpelanggan1()	);
		System.out.println(" 	tk.getIdpelanggan2()	: "+	tk.getIdpelanggan2()	);
		System.out.println(" 	tk.getIdpelanggan3()	: "+	tk.getIdpelanggan3()	);
		System.out.println(" 	tk.getKeterangan()	: "+	tk.getKeterangan()	);
		System.out.println(" 	tk.getKodeproduk()	: "+	tk.getKodeproduk()	);
		System.out.println(" 	tk.getMiscfee()	: "+	tk.getMiscfee()	);
		System.out.println(" 	tk.getMiscnumber()	: "+	tk.getMiscnumber()	);
		System.out.println(" 	tk.getNominal()	: "+	tk.getNominal()	);
		System.out.println(" 	tk.getNoref1()	: "+	tk.getNoref1()	);
		System.out.println(" 	tk.getNoref2()	: "+	tk.getNoref2()	);
		System.out.println(" 	tk.getPenalty()	: "+	tk.getPenalty()	);
		System.out.println(" 	tk.getPeriode()	: "+	tk.getPeriode()	);
		System.out.println(" 	tk.getPin()	: "+	tk.getPin()	);
		System.out.println(" 	tk.getPpn()	: "+	tk.getPpn()	);
		System.out.println(" 	tk.getProductcategory()	: "+	tk.getProductcategory()	);
		System.out.println(" 	tk.getPtname()	: "+	tk.getPtname()	);
		System.out.println(" 	tk.getRef1()	: "+	tk.getRef1()	);
		System.out.println(" 	tk.getRef2()	: "+	tk.getRef2()	);
		System.out.println(" 	tk.getRef3()	: "+	tk.getRef3()	);
		System.out.println(" 	tk.getStampduty()	: "+	tk.getStampduty()	);
		System.out.println(" 	tk.getStatus()	: "+	tk.getStatus()	);
		System.out.println(" 	tk.getSwitcherId()	: "+	tk.getSwitcherId()	);
		System.out.println(" 	tk.getUid()	: "+	tk.getUid()	);
		System.out.println(" 	tk.getWaktu()	: "+	tk.getWaktu()	);
		return tk;
	}
	public static TVKabel reqTVKabel(Payment payment){
		System.out.println("\n\n\nTVKabel ....\n\n\n");
		RequestBeans rp = new RequestBeans();
		payment.setKodeProduk("TVAORA");
		TVKabel tk = rp.getTVkabelRespone(payment);
		System.out.println(" 	tk.getAdmincharge()	: "+	tk.getAdmincharge()	);
		System.out.println(" 	tk.getBiayaadmin()	: "+	tk.getBiayaadmin()	);
		System.out.println(" 	tk.getBillamount()	: "+	tk.getBillamount()	);
		System.out.println(" 	tk.getBilleradminfee()	: "+	tk.getBilleradminfee()	);
		System.out.println(" 	tk.getBillercode()	: "+	tk.getBillercode()	);
		System.out.println(" 	tk.getBillerrefnumber()	: "+	tk.getBillerrefnumber()	);
		System.out.println(" 	tk.getBillquantity()	: "+	tk.getBillquantity()	);
		System.out.println(" 	tk.getCustomeinfo1()	: "+	tk.getCustomeinfo1()	);
		System.out.println(" 	tk.getCustomeinfo2()	: "+	tk.getCustomeinfo2()	);
		System.out.println(" 	tk.getCustomeinfo3()	: "+	tk.getCustomeinfo3()	);
		System.out.println(" 	tk.getCustomeraddress()	: "+	tk.getCustomeraddress()	);
		System.out.println(" 	tk.getCustomerId()	: "+	tk.getCustomerId()	);
		System.out.println(" 	tk.getCustomerName()	: "+	tk.getCustomerName()	);
		System.out.println(" 	tk.getDuedate()	: "+	tk.getDuedate()	);
		System.out.println(" 	tk.getIdpelanggan1()	: "+	tk.getIdpelanggan1()	);
		System.out.println(" 	tk.getIdpelanggan2()	: "+	tk.getIdpelanggan2()	);
		System.out.println(" 	tk.getIdpelanggan3()	: "+	tk.getIdpelanggan3()	);
		System.out.println(" 	tk.getKeterangan()	: "+	tk.getKeterangan()	);
		System.out.println(" 	tk.getKodeproduk()	: "+	tk.getKodeproduk()	);
		System.out.println(" 	tk.getMiscfee()	: "+	tk.getMiscfee()	);
		System.out.println(" 	tk.getMiscnumber()	: "+	tk.getMiscnumber()	);
		System.out.println(" 	tk.getNominal()	: "+	tk.getNominal()	);
		System.out.println(" 	tk.getNoref1()	: "+	tk.getNoref1()	);
		System.out.println(" 	tk.getNoref2()	: "+	tk.getNoref2()	);
		System.out.println(" 	tk.getPenalty()	: "+	tk.getPenalty()	);
		System.out.println(" 	tk.getPeriode()	: "+	tk.getPeriode()	);
		System.out.println(" 	tk.getPin()	: "+	tk.getPin()	);
		System.out.println(" 	tk.getPpn()	: "+	tk.getPpn()	);
		System.out.println(" 	tk.getProductcategory()	: "+	tk.getProductcategory()	);
		System.out.println(" 	tk.getPtname()	: "+	tk.getPtname()	);
		System.out.println(" 	tk.getRef1()	: "+	tk.getRef1()	);
		System.out.println(" 	tk.getRef2()	: "+	tk.getRef2()	);
		System.out.println(" 	tk.getRef3()	: "+	tk.getRef3()	);
		System.out.println(" 	tk.getStampduty()	: "+	tk.getStampduty()	);
		System.out.println(" 	tk.getStatus()	: "+	tk.getStatus()	);
		System.out.println(" 	tk.getSwitcherId()	: "+	tk.getSwitcherId()	);
		System.out.println(" 	tk.getUid()	: "+	tk.getUid()	);
		System.out.println(" 	tk.getWaktu()	: "+	tk.getWaktu()	);
		return tk;
	}
}
